username = "anon"
CONDASH_LOCATION = f"/home/{username}/anaconda3/etc/profile.d/conda.sh"

LEVELS = 2
PREMSEL = False
USE_M2K = False
KEEP_GENERAL = False
NOISY_DATA = False
NO_GPUS = 1 # At least 1
EXPLORATION_SAMPLE_SIZE = 1000
TEMP = 1
SIZE_FILTER = 200000
INNER_PARA = 1
BIAS_TRAINING_SAMPLES = False
PRETRAIN_NUM_EPOCHS = 20
PREMSEL_TRAIN_EPOCHS = 1
EVAL_INTERVAL = 10
